* Abstract
  We aim to design an underactuated controller which is essen- tially a off-center spinning mass that is able to steer flying vehicles. A quadcopter is used to demonstrate the principle of such controller. By in-depth analysis of the system dynamics and results from this project, we believe such principle can be applied to modern rockets with little modification.
* Introduction and Problem Statement
  Modern Rocket uses 2 DOF revolute joint to turn the nozzle to directly control the direction of thrust. Challenges are it has to resist a very high temperature and the joint need a large amount of energy to keep the nozzle in a specific direction. Instead, a precisely controlled off-center mass in the front of the rocket can create a torque that steers the Rocket.
  We aim to explore an alternative way to steer flying vehicles with underactuated controller. Taking the motivation from modern rocket control, we are going to implement such controller in a quadcopter to demonstrate such principle. We hope to extend such controller to steer rockets in a more cost and energy efficient manner.
* Mathematical Model and Matlab Implementation
  - All the equations we dervied
  - Implement these equations in matlab and solve 
* Simulation
  - Lin?
  - May want to work further
* Controller Design and Mounting
  - How we come up with the off-center mass design?
	+ why use the motor we chose? Light, pwm controllable speed
  - What are some challenges in designing the off center mass?
	+ maximum load
	+ the hole that goes in the motor
	+ mount it stably on the quad
* Control Circuit Design
  - The more technical part of the controller
	+ PWM
	+ SMD soldering
	+ Parallel battery source
* Quadcopter Hacking  
  - Control the thrust from computer
  - Control the output pwm signal from computer 
* Results
  - Simulation and Mathematical Model suggest it may work
  - Limitation in physical implementation may be the cause of unideal results
* Further Work
  - Hack the quadcopter: dynamically control the PWM output
  - How PWM pins affect the speed
  - Add sensor for spining off-center mass
* Conclusion
  - Our implementation has a lot of limitation: given the short amount of time we had
  - Proof of concept in Math Model / Simulation

